name: Build README

on:
  workflow_dispatch:
  schedule:
    - cron:  '8,28,48 * * * *'

        
jobs:
   publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Generate README.md
      uses: teoxoy/profile-readme-stats@v1
      with:
        token: ${{ secrets.GH_TOKEN }}
    - name: Update README.md
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add .
        git commit -m "Update README"
        git pull origin master
        git push -f origin master
        fi
    - name: Generate waka readme
      uses: anmol098/waka-readme-stats@master #PLEASE USE MASTER BRANCH
      with:
        WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        SHOW_PROJECTS: "False"
        SHOW_LINES_OF_CODE: "True"
        LOCALE: "en"
